### ISSUE TITLE
Retrieve and show photos described in static file

### ISSUE THREAD

**Issue by raae** [lillylabs/react-redux-gram#1]
- [ ] Set up initial project using create-react-app #2
- [ ] Design data model and create sample data #3
- [ ] Create redux store and hydrate with sample data from #4
